name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build .v file
        run: |
          docker run --rm \
            -w "/workspace" -v "${GITHUB_WORKSPACE}:/workspace" \
            mathcomp/mathcomp:latest-coq-8.10 ./build.sh
