name: check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - using: docker
        image: docker://mathcomp/mathcomp
        entrypoint: check.sh