name: check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://mathcomp/mathcomp:latest-coq-8.10
        with:
          entrypoint: check.sh
